services:
  database:
    image: postgres:16-alpine
    container_name: purga_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat_api
      POSTGRES_USER: purgato
      POSTGRES_PASSWORD: 'Purgato$123**'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - purga_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: purga_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: chat_api
      DB_USERNAME: purgato
      DB_PASSWORD: 'Purgato$$123**'
    depends_on:
      database:
        condition: service_started
    networks:
      - purga_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: purga_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000/api
      VITE_APP_URL: http://localhost:3000
    depends_on:
      backend:
        condition: service_started
    networks:
      - purga_network

volumes:
  pgdata:
  frontend_node_modules:

networks:
  purga_network:
    driver: bridge
